### ISSUE TITLE
Error: missing field api_key in deepl.toml but the key is there....

### ISSUE THREAD

**Issue by Jieiku** [hanabu/md-translate#1]
I figured it out, here is what  worked for deepl.toml, the trick was including `[glossaries]` even if you do not use them.

```toml
api_key = "redacted-redacted-redacted"

[glossaries]
"abridge" = "abridge"
"zola" = "zola"
```

here is the command I used to do the translation
`cmark-translate translate -f EN -t FR input.md output.fr.md`

It seems using glossaries is not a required feature so it would be nice for this tool to still work even if `[glossaries]` is missing in the deepl.toml file.

**Comment by Jieiku** [comment]
I figured it out, but this tool does not work good for markdown that contains shortcodes....

here is what  worked for deepl.toml

```toml
api_key = "redacted-redacted-redacted:fx"

[glossaries]
"abridge" = "abridge"
"zola" = "zola"
 
[ignores]
abridge = [
  "Abridge",
  "Zola",
]
```
